---
# prometheus/tasks/main.yml
scrape_configs:
  - job_name: "control"
    static_configs:
      - targets: ["192.168.56.100:9100"]
  - job_name: "vm1"
    static_configs:
      - targets: ["192.168.56.101:9100"]
  - job_name: "vm2"
    static_configs:
      - targets: ["192.168.56.102:9100"]
