---
# roles/enroll/tasks/main.yml
- name: Create a user 'ava' with a home directory
  ansible.builtin.user:
    name: ava
    create_home: yes

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: ava
    state: present
    key: "{{ lookup('authorized_keys', 'home/ava/.ssh/id_rsa.pub')}}"

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ans
    dest: /etc/sudoers.d/ans
    owner: root
    group: root
    mode: '0644'
