#!/bin/bash
# set -o xtrace

function initialize (){
trap 'summarize; exit 0' INT
num_ques=0
num_correct=0
first_time=true
cd ${CONFDIR=~/proj01/conf} || exit 2
}

function choose_conf (){
confs=($(ls))
PS3='Choose a configuration directory from the following list: '
select Conf in ${confs[@]}; do
        if [[ -z "$Conf" ]]; then
                echo "No configuration directory. Bye."
                exit 1
        fi
        echo $Conf
        return 0
done
}

function check_conf(){
        if [ ! -f .info ]; then
                echo "No .info file found. Bye"
                exit 1
        fi

        required=$(cut -d: -f1 .info)
        sudo_needed=$(cut -d: -f2 .info)
        files=$(cut -d: -f3 .info)
        cmd=$(cut -d: -f4 .info)

        if [ ! -f $required ] || [ ! -x $required ]; then
                echo "Required command not found or not executable!"
                exit 1
        fi

        files_cut=$(echo $files | tr ',' ' ')

        for f in $files_cut; do
		(( num_conf++ ))
    		if [ ! -f "$f" ]; then
        		echo "Missing file $f from .info"
        		continue
    		fi

    		# Substitute @filepath with the full path and execute
    		execute=$(echo "$cmd" | sed "s|@filepath|$(pwd)/$f|")

    		if [ "$sudo_needed" == "yes" ]; then
        		sudo $execute
    		else
        		$execute
    		fi

    		# Check command result
    		if [ $? -eq 0 ]; then
        		(( num_correct++ ))
        		echo "Configuration file $f passed test."
    		else
        		echo "Configuration file $f failed test."
    		fi
	done

	echo "<html><body>" > report.html
	echo "<h1>Configuration File Checker Report for $conf</h1>" >> report.html
	echo "<table>" >> report.html
	echo "<tr><th>File</th><th>Pass</th><th>Reason</th></tr>" >> report.html

	for f in $files_cut; do
    		if [ -f $f ]; then
        		echo "<tr><td>$f</td><td><b>PASS</b></td><td>SUCCESS</td></tr>" >> report.html
    		else
        		echo "<tr><td>$f</td><td><b>FAIL</b></td><td>Missing file</td></tr>" >> report.html
    		fi
	done

	echo "</table>" >> report.html
	echo "<br><br>Generated by my glorious PROJ01 script!" >> report.html
	echo "</body></html>" >> report.html
}

function summarize (){
        echo "Out of $num_conf configuration files, $num_correct were successful."
}

# Main Program
initialize

conf=$(choose_conf)
[[ $? -eq 0 ]] || exit 2
cd $conf || exit 2
check_conf

summarize
