---
# roles/enroll/tasks/main.yml
- name: Create Ansible user
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    become: true

- name: Add public key to Ansible user
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '/home/user/.ssh/id_rsa.pub') }}"

- name: Allow ansible user passwordless sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ans
    content: "ansible ALL=(ALL) NO PASSWD: ALL\n"
    mode: '0440'
