---
# roles/enroll/tasks/main.yml
- name: Create Ansible user
  ansible.builtin.user:
    name: "ava"
    state: present
    shell: /bin/bash
    comment: "Ansible Management User"

- name: Install SSH public key for Ansible user
  ansible.posix.authorized_key:
    user: "ava"
    state: present
    key: "lookup('authorized_keys', /home/ava/.ssh/id_rsa.pub)"

- name: Create sudoers file for Ansible user
  ansible.builtin.copy:
    src: ans
    dest: /etc/sudoers.d/ans
    mode: "0440"
    validate: "/usr/sbin/visudo -cf %s"
