---
# This playbook installs a banana website on the server.
- name: Install NGINX
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes
  tags:
    - nginx
    - banana

- name: Download banana
  ansible.builtin.get_url:
    url: "http://scrivnor.cikeys.com/files/website.tar.gz"
    dest: /tmp/banana.jpg
  tags:
    - banana

- name: Untar banana
  ansible.builtin.unarchive:
    src: /tmp/banana-website.tar.gz
    dest: /var/www/
    remote_src: yes
  tags:
    - banana

- name: Install banana website
  ansible.builtin.copy:
  src: /var/www/banana-website
  dest: /var/www/html/
  owner: www-data
  group: www-data
  mode: '0755'
  remote_src: yes
  tags:
    - banana  

- name: Set up the permissions for banana
  ansible.builtin.file:
    path: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0744'
    recurse: yes
  tags:
    - banana
    - permissions

- name: Restart NGINX
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
  tags:
    - nginx
    - banana

- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: latest
    update_cache: yes
  tags:
    - firewall
    - security

- name: Allow SSH connections (port 22)
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow HTTP connections (port 80)
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: allow
