---
# Create new users and their SSH keys
- name: Create new users
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell: /bin/bash
  loop: "{{ vms }}"

- name: Create SSH keys
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ vms }}"
  become: true

- name: Copy and add SSH keys
  ansible.builtin.copy:
    src: "{{ item.name }}.pub"
    dest: "/home/{{ item.name }}/.ssh/authorized_keys"
    mode: '0600'
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ vms }}"
  become: true

- name: Install SSH keys
  ansible.builtin.package:
    name: openssh-server
    state: present
  become: true
  loop: "{{ vms }}"
