---
# roles/ftp/tasks/main.yml
- name: Install vsftpd
  ansible.builtin.package:
    name: vsftpd
    state: present

- name: Enable service vsftpd and ensure it is not masked
  ansible.builtin.systemd_service:
    name: vsftpd
    enabled: true
    masked: no

- name: Make sure a service unit is running
  ansible.builtin.systemd_service:
    state: started
    name: vsftpd

- name: Create a user 'ftp_user' with a home directory
  ansible.builtin.user:
    name: ftp_user
    create_home: yes
