---
# examples/tasks/main.yml
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: foo
    dest: /root/foo
    owner: root
    group: root
    mode: '0644'

- name: Install tmux
  ansible.builtin.package:
    name: tmux
    state: present
